language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

after_script:
  - travis_retry php vendor/bin/coveralls -v

script:
  - vendor/bin/phpunit --verbose
